### ISSUE TITLE
Demo of usage

### ISSUE THREAD

**Issue by amilajack** [joshwcomeau/redux-vcr#2]
Would be great if there was a small gif or demo exemplifying the usage of this module.

**Comment by joshwcomeau** [comment]
Hey!

Truthfully, this skunkworks project of mine is not yet ready for primetime; I tend to forget that stuff on GitHub is actually public.

That said, I've been using it in production and it's performed brilliantly so far. So I should put some work into making this release "official".

You can [play with a demo here](http://keyandpad.com/?adminMode=true), with real production data. And I'll add a GIF shortly :)

**Comment by amilajack** [comment]
Great. Thanks!

**Comment by amilajack** [comment]
Should I keep this open?

**Comment by joshwcomeau** [comment]
Nah, it's fine to keep it closed. :+1:
